name = "testpack"
author = "rojok"
version = "1.18"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09cb1e874981965855d07b7f5b4a3599e09d1c78777b90d5671f6f8abc4886c9"

[versions]
forge = "38.0.16"
minecraft = "1.18"
