name = "AppleSkin"
filename = "appleskin-forge-mc1.18-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/846/appleskin-forge-mc1.18-2.2.0.jar"
hash-format = "murmur2"
hash = "2799136209"

[update]
[update.curseforge]
file-id = 3549846
project-id = 248787
