name = "Aquaculture 2"
filename = "Aquaculture-1.18-2.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/695/Aquaculture-1.18-2.3.0.jar"
hash-format = "murmur2"
hash = "1913974952"

[update]
[update.curseforge]
file-id = 3545695
project-id = 60028
