name = "Balm (Forge Edition)"
filename = "balm-2.3.0+0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3558/757/balm-2.3.0+0.jar"
hash-format = "murmur2"
hash = "671266018"

[update]
[update.curseforge]
file-id = 3558757
project-id = 531761
