name = "Just Enough Items (JEI)"
filename = "jei-1.18-9.0.0.40.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/20/jei-1.18-9.0.0.40.jar"
hash-format = "murmur2"
hash = "44838827"

[update]
[update.curseforge]
file-id = 3550020
project-id = 238222
