name = "Mouse Tweaks"
filename = "MouseTweaks-forge-mc1.18-2.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3578/801/MouseTweaks-forge-mc1.18-2.21.jar"
hash-format = "murmur2"
hash = "547207357"

[update]
[update.curseforge]
file-id = 3578801
project-id = 60089
