name = "Pollution of the Realms"
filename = "AdPother-1.18.1-5.0.0.0-build.0049.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/295/AdPother-1.18.1-5.0.0.0-build.0049.jar"
hash-format = "murmur2"
hash = "1145255159"

[update]
[update.curseforge]
file-id = 3587295
project-id = 269973
